# Docker Compose configuration for Jupyter Notebook and MySQL
# Utilizo un init-container para descargar la base de datos de inicio.

services:

  notebook:
    image: "quay.io/jupyter/scipy-notebook:latest"
    ports:
      - "8888:8888"
    volumes:
      - ..:/home/jovyan/work/bdge
    user: root
    environment:
      - NB_UID=${DUID}
      - NB_GID=${DGID}
      - CHOWN_HOME=yes
      - JUPYTER_TOKEN=bdge
      - GRANT_SUDO=yes
      - DB_HOSTNAME=mysql
    depends_on:
      mysql:
        condition: service_healthy

  init-db:
    image: alpine:latest
    working_dir: /workspace
    user: "${DUID}:${DGID}"
    volumes:
      - .:/workspace
    init: true
    entrypoint: /workspace/scripts/init-alpine-container.sh
    healthcheck:
      test: ["CMD", "test", "-e", "/workspace/data/done"]
      interval: 10s
      timeout: 3s
      retries: 15
      start_period: 20s

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 20s
      start_period: 60s
      start_interval: 10s
      timeout: 5s
      retries: 100
    depends_on:
      init-db:
        condition: service_healthy
